import { Parkinsans } from 'next/font/google'
import {UserProvider} from '../context/UserContext'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from '@/components/app-sidebar';
import Nav from '@/components/Nav';
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const parkinsans = Parkinsans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Optional: choose desired font weights
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={parkinsans.className}
      >
        <UserProvider>
          <SidebarProvider >
            <AppSidebar  />
            <main className="w-full md:px-4 md:p-2 p-2">
              <div className="flex justify-around mb-5">
                <SidebarTrigger />
                <Nav />
              </div>
              {children}
            </main>
          </SidebarProvider>
        </UserProvider>
      </body>
    </html>
  );
}
